# Generated by Django 5.0.3 on 2024-04-15 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cadastro',
            new_name='CadastroDB',
        ),
    ]
